import { Heading, Hr, Link, Section, Text } from "react-email";

export const APP_URL = "https://meeting-intelligence.victorscheike.com";

export function BrandHeader() {
  return (
    <Section>
      <Text className="m-0 text-xs font-semibold uppercase tracking-wide text-brand-muted">
        Meeting Intelligence
      </Text>
    </Section>
  );
}

export function EmailFooter() {
  return (
    <Section>
      <Hr className="border-solid border-brand-border my-6" />
      <Text className="m-0 text-xs leading-5 text-brand-muted">
        This brief was generated by Meeting Intelligence. Recipients can act on
        the next steps in this email without opening the Original meeting notes.
      </Text>
      <Text className="mt-2 mb-0 text-xs leading-5 text-brand-muted">
        <Link href={APP_URL} className="text-brand-accent underline">
          Open Meeting Intelligence
        </Link>
      </Text>
    </Section>
  );
}

type NextStep = {
  text: string;
  due?: string;
};

export function NextSteps({
  people,
}: {
  people: Array<{ name: string; nextSteps: NextStep[] }>;
}) {
  const assigned = people.filter((person) => person.nextSteps.length > 0);

  if (assigned.length === 0) {
    return (
      <Text className="text-sm leading-6 text-brand-muted">
        No named next steps were assigned in this brief.
      </Text>
    );
  }

  return (
    <>
      {assigned.map((person) => (
        <Section key={person.name} className="mb-5">
          <Heading
            as="h3"
            className="mt-0 mb-3 text-base font-semibold text-brand-ink"
          >
            {person.name}
          </Heading>
          {person.nextSteps.map((step) => (
            <StepRow key={`${person.name}-${step.text}`} step={step} />
          ))}
        </Section>
      ))}
    </>
  );
}

export function PersonSteps({ steps }: { steps: NextStep[] }) {
  if (steps.length === 0) {
    return (
      <Text className="text-sm leading-6 text-brand-muted">
        No named next steps were assigned to this person.
      </Text>
    );
  }

  return (
    <>
      {steps.map((step) => (
        <StepRow key={step.text} step={step} />
      ))}
    </>
  );
}

function StepRow({ step }: { step: NextStep }) {
  return (
    <Section className="mb-3 border-none border-l border-solid border-l-brand-accent pl-3">
      <Text className="m-0 text-sm leading-6 text-brand-ink">{step.text}</Text>
      {step.due ? (
        <Text className="mt-1 mb-0 text-xs leading-5 text-brand-muted">
          {`Due ${step.due}`}
        </Text>
      ) : null}
    </Section>
  );
}
